package(default_visibility = ["//visibility:public"])


#exports_files(["jodreports-cli.jar"])


java_import(
        name = "jodreports",
        jars = [
	     "jodreports-2.4.1-with-dependencies.jar"
            #"jodreports-cli.jar"
        ],
)
